remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Anti-Food]
description: [Scan ingredient lists instantly to bypass buzzwords and make healthier, informed choices with our app.]